### ISSUE TITLE
The link to bootstrap.dat is broken.

### ISSUE THREAD

**Issue by talkingtab** [znation/scalable-data-visualization#2]
The bootstrap.dat link in the README.md gets a 404.
Any chance of getting a _small_ set of data as well?

**Comment by znation** [comment]
Sorry about that. I'll try to find a place to host the data.

**Comment by znation** [comment]
I will put the data up on S3 -- I'm traveling right now but when I have a good enough internet connection I'll update the README with a new link. Thanks for letting me know!

I don't have a good way to create a smaller dataset but if you happen to come across one I'll be happy to host that or link to it as well.

**Comment by talkingtab** [comment]
Thanks! Looking forward to getting a link.

**Comment by znation** [comment]
You're welcome! Thanks for being patient!

FIxed with 33acf3470664d8eda9b143edb5e86d4219cc4f97.
